name: PR

on:
  pull_request:
    branches: [main]

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      PACKAGE_NAME: FollowAlong
      SOLUTION_NAME: FollowAlong.sln
      PUBLISH_ARTIFACTS: false
